plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

group = project.maven_group
version = project.mod_version

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = 'GeckoLib'
				url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
			}
		}
		filter { includeGroupAndSubgroups('com.geckolib') }
	}
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/releases/'
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation "com.terraformersmc.terraform-api:terraform-wood-api-v1:${project.terraformer_version}"
	include "com.terraformersmc.terraform-api:terraform-wood-api-v1:${project.terraformer_version}"
	implementation "com.geckolib:geckolib-fabric-${project.minecraft_version}:${project.geckolib_version}"
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraft_version", minecraft_version
	inputs.property "loader_version", loader_version
	inputs.property "java_version", java_version
	inputs.property "geckolib_version", geckolib_version
	inputs.property "loom_version", loom_version

	filesMatching("fabric.mod.json") {
		expand(
				"version": project.version,
				"minecraft_version": minecraft_version,
				"loader_version": loader_version,
				"java_version": java_version,
				"loom_version": loom_version,
				"geckolib_version": geckolib_version,
		)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release.set(java_version as Integer)
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.toVersion(java_version)
	targetCompatibility = JavaVersion.toVersion(java_version)
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName
	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
